spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

frontend:
  url: ${FRONTEND_URL}

jwt:
  secret_key: H_QeUmAczHfkcGGrgyDGVvGnHDDvcthMufahi1ZwW2w

server:
  port: 8080